### ISSUE TITLE
Questions re 2015 snippet

### ISSUE THREAD

**Issue by adamlofting** [ScottDowne/eoy-snippets#7]
<img width="667" alt="screenshot 2015-09-22 10 00 33" src="https://cloud.githubusercontent.com/assets/1901816/10014389/cbf2cf82-6110-11e5-8ab3-f99fddfde793.png">
- [x] If we go live with the old donation form, the currency will need to be USD - can we change this as a config option in the snippet?
- [x] The currency isn't currently being passed through to the new donation form (you end up in USD even through the form is in EUR) - is there an open ticket for this already?

**Comment by ScottDowne** [comment]
Second item in the checklist is fixed: http://scottdowne.github.io/eoy-snippets/2015-snippet/

**Comment by ScottDowne** [comment]
Going with the old snippet for legacy form.

http://scottdowne.github.io/eoy-snippets/simple-snippet/

new is here: 

http://scottdowne.github.io/eoy-snippets/2015-snippet/
